# baseURL = 'https://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'
# theme = 'hugo-brewm'

## Base URL for the site
baseURL = 'diktam.me'
## Site title
title = 'D'
## Use hugo-brewm theme
theme = 'hugo-brewm'
## Enable Git information for pages, (e.g. lastMod date information)
enableGitInfo = false
## Convert all URLs to absolute URLs
canonifyURLs = false
## Default language for content
defaultContentLanguage = 'zh'
## Put default language in subdirectory
defaultContentLanguageInSubdir = false
## Generate a robots.txt
enableRobotsTXT = true
## Use sections for main menu
sectionPagesMenu = 'main'
## Files to ignore when building site
ignoreFiles = ['\.redacted', '\.old', '\.bak', '\.tmp', '\.swp', '\.DS_Store']

[caches]
[caches.images]
dir = ':cacheDir/images'


[[menu.main]]
identifier = "post"
name = "æ‰€æœ‰å†…å®¹"
url = "/post/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "åœ°å›¾"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "author"
name = "ä½œè€…"
url = "/author/"
weight = 3


## Enable code fence highlighting
[markup]
[markup.highlight]
codeFences = false

## Sitemap configuration
[sitemap]
# Change frequency setting (will affect posts listings layout): 'always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never'
changeFreq = 'always'

## Site parameters
[params]
favicon = "/images/favicon.svg"
## Site title
title = "å¤§å¤§çš„åœŸè±†ğŸ¥”miao"
## Site description
description = "è¿™æ˜¯ä¸€ä¸ªæè¿°ğŸ±"
## Copyright notice, not implemented yet
# copyright = "Copyright 2025 (c) Author"
## Enable extended metadata (social cards)
extMeta = false
## Enable coffee metric
coffeeStat = false
## Default social card image, recommended resolution: 1200 x 630px
# images = "example.com/img/social-share.jpg" 


## Author information
[params.author]
name = 'Dik Tam'
email = 'diktamxx@gmail.com'
## è‡ªå®šä¹‰ä½œè€…å’Œåˆè‘—è€…ä¿¡æ¯çš„å…¶ä»–æ–¹æ³•
# coauthor = [
#     {name = "å¼ ä¸‰", bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}
# ]

## Comments configuration
[params.comments]
## Disable comments (disable fediverse comments)
disabled = true
## Comment platform selection, currently only 'fediverse' is supported, further options to be determined
# platform = 'fediverse'
## Fediverse integration settings
[params.fediverse]
## Fediverse instance URL
instance = 'example.com'
## Fediverse username
username = 'username'

## Logo configuration
[params.logo]
## Light mode logo mark
# logoMark = 'https://example.com/logoMark.svg'
## Dark mode logo mark
# logoMarkDark = 'https://example.com/logoMarkDark.svg'
## Enable logo type
logoType = true

## Feed display settings
[params.feed]
## Enable flowlines
flowlines = true
## Limit number of flowlines with maximum 42
flowlinesLimit = 21

## Home page display settings
[params.home]
## Disable slide carousel
disableSlide = false
## Disable taxonomy listing carousel
disableListing = false

## Post display settings
[params.posts]
## Enable text justification
justifying = false
## Disable paragraph indentation
noIndent = false
## Show colophon section (including QR code)
colophon = false
## disable redaction history
disableHistory = false
## Show related content
related = true
## Show share buttons
share = false

## Search configuration
[params.search]
## Enable search functionality, please index your site first
enable = false
## Use pagefind search when javascript enabled, currently only 'pagefind' is supported, further options to be determined
pagefind = false
## fallback searchbox when javascript disabled, currently the options limited to 'mojeek', otherwise duckduckgo will be used
# fallback = 'mojeek'

## Typography settings
[params.typeface]
## Use web safe fonts (will overide font selection below)
webSafe = false
## Serif font selection
roman = 'crimson'
## Sans-serif font selection
sans = 'inter'

## Extended Metadata and Social card configuration
[params.socialCard]
## Enable twitter and opengraph social cards (same as .params.extMeta)
enable = false
## Default social card image, same as .Params.images
# images = "img/social-share.jpg" 
## Enable Twitter cards
# twitter = true
## Twitter creator handle
# twitterCreator = "@username"
## Twitter site handle
# twitterSite = "@username"

## Enable OpenGraph
# opengraph = true
## Facebook App ID
# facebookAppID = "123456789"
## Facebook Admin ID
# facebookAdmin = "USER_ID"

## Schema.org (EXPERIMENTAL, not fully supported body tags)
# schema = true
## JsonLD (EXPERIMENTAL, cannot validate permalink)
# jsonLD = true
